
image: maven:3.8.1-jdk-11-openj9



stages:          
  - build
  - test
  - deploy
  - check



check-job :
  stage: check
  script : 
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=41120086

