
image: maven:3.8.1-jdk-11-openj9

stages:          
  - build
  - test
  - deploy
  - check

#build-job:       
 # stage: build
  #script:
   #   - mvn package -DskipTest

#test-job:
 # stage: test
  #script:
   # - mvn test

check-job :
  stage: check
  script : 
    - mvn verify        



